[tool.poetry]
name = "sales-management-api"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.8"
httpx = "^0.28.1"
uvicorn = "^0.34.0"


[tool.poetry.group.dev.dependencies]
httpie = "^3.2.4"
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
